# Write a function so that the columns of the output matrix are powers of the input vector.
#The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [2]:
# x  = 1d array
# i = number of columns
# increasing = change of power will be from left to right if increasing =  True and vice versa.
import numpy as np
x = np.array([1, 2, 3, 5])
print(np.vander(x,increasing = False))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [3]:
# by changing the number of columns

k = 5
print(np.vander(x,k,increasing = False))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [625 125  25   5   1]]


In [4]:
# by making increasing as True
print(np.vander(x,k,increasing = True))


[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   5  25 125 625]]


# Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
n = [10,20,30,40,50,60,70,80,90,100]
k = 4
count = 0
index = 0
while index < len(n) - k + 1:
    sum = 0
    for i in range(index,k+index):
        sum = sum + n[i]
    print(sum//k)
    count += 1
    index += 1
print('moving average sequence has',count,'values')

25
35
45
55
65
75
85
moving average sequence has 7 values


# Alternate method

In [6]:
n = [10,20,30,40,50,60,70,80,90,100]
k = 4
r = np.convolve(n,np.ones(k),'valid')/k
print(r)

[25. 35. 45. 55. 65. 75. 85.]
